### ISSUE TITLE
uncertain cells in nucleotide data

### ISSUE THREAD

**Issue by DMaddison** [nexml/nexml.java#14]
In Mesquite, when exporting a nucleotide file, and exception is thrown if there are uncertain cells in the matrix (e.g. R =A/G). Should be able to export these without complaint using the ambiguity codes.

**Comment by rvosa** [comment]
Hi David,

Is this actually a manifestation of the case sensitivity of the alphabet - as per your email - or do we have a bug that chokes on valid IUPAC ambiguity codes? This really _should_ work if the case is right. Would you mind pasting the stack trace in here (if you have one)?

**Comment by rvosa** [comment]
I reproduced the stack trace you got in Mesquite from the file you sent me. The trace starts out with a message about "A/G" not being valid as a symbol. This happens because the NeXML serializer actually wants the IUPAC symbol ("R") as a string, and not its constituent fundamental states. It uses this to do some internal lookups to map the symbol to a state ID. For some reason the NeXML serializer for Mesquite has been using `state.toDisplayString()` for this, which works fine for unambiguous states but apparently not for ambiguous ones. 

So how then would I get the ambiguity symbol itself, i.e. "R"? 

I'm getting the impression that this should happen by way of `state.toNEXUSString()`, is that the recommended way? 

If so, is there an elegant way in which this method could be made available both for categorical as well as continuous character state values? 

Ideally, `toNEXUSString` would be a method of CharacterState instead of CategoricalState. Alternatively, we'd have to do a bit of `instanceof` checking inside the serializer, which is not the most elegant thing in the world, but obviously acceptable if we have to.
